version: '2'
services:
    intercolis-app:
        image: intercolis
        external_links:
            - intercolis-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/intercolis
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    intercolis-postgresql:
        extends:
            file: postgresql.yml
            service: intercolis-postgresql
